{
 "title": "Dashboard - Squad B2B/Wealth",
 "description": "Basic measurements of request handling using data from prometheus-net middleware",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(http_requests_received_total, instance)"
   },
   {
    "name": "controllers",
    "label": "Controllers",
    "query": "label_values(http_requests_received_total{instance =~ \"$instances\"}, controller)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tentativas de login com sucesso nos últimos 7 dias.",
   "type": "stat",
   "description": "Contabiliza tentativas de login com sucesso nos últimos 7 dias.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "guias_portal_login_sucess_last_days_counter{instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Tentativas de login sem sucesso nos últimos 7 dias.",
   "type": "stat",
   "description": "Contabiliza tentativas de login sem sucesso nos últimos 7 dias.",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "guias_portal_login_error_last_days_counter{instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Acessos realizados por usuário com sucesso nos últimos 7 dias",
   "type": "graph",
   "description": "contabiliza acessos realizados por usuário com sucesso nos últimos 7 dias",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "guias_portal_login_per_user_success_counter",
     "legendFormat": "{{user_name}}"
    },
    { "legendFormat": "(None)" }
   ]
  },
  {
   "title": "Acessos realizados por usuário sem sucesso nos últimos 7 dias",
   "type": "graph",
   "description": "contabiliza acessos realizados por usuário sem sucesso nos últimos 7 dias",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "guias_portal_login_per_user_error_counter",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Quantidade de requisições por endpoints - ApProductsService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ap_product_service_path_counter{endpoint=\"/fidex-income/characteristics\",instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/fidex-income/characteristics"
    },
    {
     "expr": "ap_product_service_path_counter{endpoint=\"/funds\",instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/funds"
    },
    {
     "expr": "ap_product_service_path_counter{endpoint=\"/variable-income/clients\",instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/variable-income/clients"
    },
    {
     "expr": "ap_product_service_path_counter{endpoint=\"/funds/characteristics\",instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/funds/characteristics"
    },
    {
     "expr": "ap_product_service_path_counter{endpoint=\"/types/custody-assets\",instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/types/custody-assets"
    },
    {
     "expr": "ap_product_service_path_counter{endpoint=\"/variable-income/assets\",instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/variable-income/assets"
    },
    {
     "expr": "ap_product_service_path_counter{endpoint=\"/funds/rentability-product\",instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/funds/rentability-product"
    }
   ]
  },
  {
   "title": "Ap Products Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"ap-products-service.qa.guideinvestimentos.com.br:80\",job=\"ap_product_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por endpoints - OrgUnitAdvisorManagementService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_unit_advisor_mangement_service_path_counter{endpoint=\"/advisors-portal/list-advisor-name\",instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/advisors-portal/list-advisor-name"
    },
    {
     "expr": "org_unit_advisor_mangement_service_path_counter{endpoint=\"/advisors-portal/cpf/35558721847\",instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/advisors-portal/cpf/{cpf}"
    },
    {
     "expr": "org_unit_advisor_mangement_service_path_counter{endpoint=\"/advisors-portal/list-advisor-data\",instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/advisors-portal/list-advisor-data"
    },
    {
     "expr": "org_unit_advisor_mangement_service_path_counter{endpoint=\"/advisors\",instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/advisors"
    },
    {
     "expr": "org_unit_advisor_mangement_service_path_counter{endpoint=\"/advisor-mirror/92210855039\",instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/advisor-mirror/{cpf}"
    },
    {
     "expr": "org_unit_advisor_mangement_service_path_counter{endpoint=\"/advisor-mirror\",instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/advisor-mirror"
    }
   ]
  },
  {
   "title": "OrgUnit Advisor Management Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por endpoints - ApPortfoliosService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/rentability-last-months\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/rentability-last-months"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/rentability-gross\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/rentability-gross"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/rentability-gross\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/rentability-gross"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/rentability-asset-class\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/rentability-asset-class"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/rentability\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/rentability"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/overview\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/overview"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/movements-account/additional-inform-year\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/movements-account/additional-inform-year"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/movements-account/account\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/movements-account/account"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/invoice/fixed-income\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/invoice/fixed-income"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/future-release/future-release-provents\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/future-release/future-release-provents"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/custody/asset-classes\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/portfolio/custody/asset-classes"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/consolidated/period\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/portfolio/consolidated/period"
    },
    {
     "expr": "ap_portfolios_service_path_counter{endpoint=\"/portfolio/consolidated/download\",instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/portfolio/consolidated/download"
    }
   ]
  },
  {
   "title": "Ap Portfolio Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"ap-portfolios-service.qa.guideinvestimentos.com.br:80\",job=\"ap_portfolios_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por endpoints - ApCustomerService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ap_customer_service_path_counter{endpoint=\"/clients_advisor_portal\",instance=\"ap-customer-service.qa.guideinvestimentos.com.br:80\",job=\"ap_consumer_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/clients_advisor_portal"
    },
    {
     "expr": "ap_customer_service_path_counter{endpoint=\"/clients-advisor/sinacor\",instance=\"ap-customer-service.qa.guideinvestimentos.com.br:80\",job=\"ap_consumer_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/clients-advisor/sinacor"
    },
    {
     "expr": "ap_customer_service_path_counter{endpoint=\"/client-accounts/sinacorcodes\",instance=\"ap-customer-service.qa.guideinvestimentos.com.br:80\",job=\"ap_consumer_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/client-accounts/sinacorcodes"
    },
    {
     "expr": "ap_customer_service_path_counter{endpoint=\"/\",instance=\"ap-customer-service.qa.guideinvestimentos.com.br:80\",job=\"ap_consumer_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/"
    }
   ]
  },
  {
   "title": "Ap Customer Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"advisors-management.org-unit.qa.guideinvestimentos.com.br:80\",job=\"org_unit_advisor_mangement_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por endpoints - ApSecurityService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ap_security_service_path_counter{endpoint=\"/load-portal-data\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/load-portal-data"
    },
    {
     "expr": "ap_security_service_path_counter{endpoint=\"/google-recaptcha\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/google-recaptcha"
    },
    {
     "expr": "ap_security_service_path_counter{endpoint=\"/two-factor-authenticators/generate\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/two-factor-authenticators/generate"
    },
    {
     "expr": "ap_security_service_path_counter{endpoint=\"/two-factor-authenticators/current-pin\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/two-factor-authenticators/current-pin"
    },
    {
     "expr": "ap_security_service_path_counter{endpoint=\"/two-factor-authenticators/validate\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/two-factor-authenticators/validate"
    },
    {
     "expr": "ap_security_service_path_counter{endpoint=\"/two-factor-authenticators​/save​\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/two-factor-authenticators​/save"
    },
    {
     "expr": "ap_security_service_path_counter{endpoint=\"/two-factor-authenticators/has-two-factor​\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/two-factor-authenticators/has-two-factor"
    },
    {
     "expr": "ap_security_service_path_counter{endpoint=\"​/two-factor-authenticators/remove\",instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/two-factor-authenticators/remove"
    }
   ]
  },
  {
   "title": "Ap Security Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"qa-node8.aws.guideinvestimentos.com.br:9240\",job=\"ap_security_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por endpoints - ApAsappService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ap_asapp_service_path_counter{endpoint=\"/categories\",instance=\"ap-asapp-service.qa.local:80\",job=\"ap_asapp_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/categories"
    },
    {
     "expr": "ap_asapp_service_path_counter{endpoint=\"/posts\",instance=\"ap-asapp-service.qa.local:80\",job=\"ap_asapp_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/posts"
    },
    {
     "expr": "ap_asapp_service_path_counter{endpoint=\"/posts/read\",instance=\"ap-asapp-service.qa.local:80\",job=\"ap_asapp_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/posts/read"
    }
   ]
  },
  {
   "title": "Ap Asapp Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"ap-asapp-service.qa.local:80\",job=\"ap_asapp_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por endpoints - ApAlertsService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ap_alerts_service_path_counter{endpoint=\"/occurrences/categories\",instance=\"ap-alerts-service.qa.local:80\",job=\"ap_alerts_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/occurrences/categories"
    },
    {
     "expr": "ap_alerts_service_path_counter{endpoint=\"/occurrences/customers\",instance=\"ap-alerts-service.qa.local:80\",job=\"ap_alerts_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/occurrences/customers"
    },
    {
     "expr": "ap_alerts_service_path_counter{endpoint=\"/occurrences/change-status\",instance=\"ap-alerts-service.qa.local:80\",job=\"ap_alerts_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/occurrences/change-status"
    }
   ]
  },
  {
   "title": "Ap Alerts Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"ap-alerts-service.qa.local:80\",job=\"ap_alerts_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Quantidade de requisições por endpoints - ApOrdersService",
   "type": "bargauge",
   "description": "quantifica a quantidade de vezes que o endpoint foi requisitado",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ap_orders_service_path_counter{endpoint=\"/orders/vm\",instance=\"ap-orders-service.qa.guideinvestimentos.com.br:80\",job=\"ap_orders_service_image-read-prometheus\",method=\"POST\"}",
     "legendFormat": "/orders/vm"
    },
    {
     "expr": "ap_orders_service_path_counter{endpoint=\"/orders/status\",instance=\"ap-orders-service.qa.guideinvestimentos.com.br:80\",job=\"ap_orders_service_image-read-prometheus\",method=\"GET\"}",
     "legendFormat": "/orders/status"
    },
    {}
   ]
  },
  {
   "title": "Ap Orders Service",
   "type": "stat",
   "description": "verifica se a api está recebendo requisições",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"ap-orders-service.qa.guideinvestimentos.com.br:80\",job=\"ap_orders_service_image-read-prometheus\"}"
    }
   ]
  },
  {
   "title": "Em Progresso (global)",
   "type": "singlestat",
   "description": "Em TODOS os controladores globalmente!",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_requests_in_progress{instance =~ \"$instances\"})"
    }
   ]
  },
  {
   "title": "Total req/s",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 49 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m]))"
    }
   ]
  },
  {
   "title": "Taxa de requisições por segundos recebidas por controllers",
   "type": "graph",
   "description": "contabiliza todas as requisições, tanto com sucesso como com falhas.",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\",  code !~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\",  code !~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m]))",
     "legendFormat": "(None)"
    }
   ]
  },
  {
   "title": "Duração das Requisições (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{instance =~ \"$instances\", controller =~ \"$controllers\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Taxa de requisições de erro por segundos por controller",
   "type": "graph",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{instance=~\"$instances\", controller=~\"$controllers\", code=~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{instance=~\"$instances\",controller=\"\", code=~\"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}